name: 'Dump variables'
description: 'Dump github variables and secrets'
inputs:
  the_secrets:
    description: 'The secrets variable'
    required: true

runs:
  using: "composite"
  steps:
      - name: 'Dump Env and Secrets'
        shell: bash
        run: |
          env > env.txt
          echo $SECRETS_CONTEXT >> env.txt
        env:
          SECRETS_CONTEXT: ${{inputs.the_secrets}}
      
      - name: 'Upload env Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: env
          retention-days: 1
          path: |
            env.txt

