name: 'Dump variables'
description: 'Dump github variables and secrets'
inputs:
  the_secrets:
    description: 'The secrets variable'
    required: true

runs:
  using: "composite"
  steps:
      - name: 'Dump Env and Secrets'
        shell: bash
        run: |
          echo "${{vars.PASSWORD_SVC_S2S_USER}}"
          env > env.txt
          echo "${{inputs.the_secrets}}" >> env.txt
          echo "${{vars.PASSWORD_SVC_S2S_USER}}" >> env.txt
      
      - name: 'Upload env Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: env
          retention-days: 1
          path: |
            env.txt

